### ISSUE TITLE
Add component_id to incidents call

### ISSUE THREAD

**Issue by djtecha** [dmsimard/python-cachetclient#3]
it would be nice to tie an incident to a component liek:

new_incident = json.loads(incidents.post(name=SERVICE,
                                         message=DESCRIPTION,
                                         status=STATUS,
                                         component_id=14))

currently i'm just toggling the status and description of a component then making an incident but it doesn't have the nice UI when one does that.

**Comment by ignitedPotato** [comment]
Have a look at https://docs.cachethq.io/reference#incidents

component_id must come with component_status to work. This client already supports adding arbitrary parameters

**Comment by djtecha** [comment]
Ahh cool, looks like the latest version supports this now. Thanks!
