### ISSUE TITLE
Update pip repository

### ISSUE THREAD

**Issue by janboll** [dmsimard/python-cachetclient#6]
Hi,

Could you please update the public Python Package Index with the latest version of this library?
This patch for instance is not in the repo version: https://github.com/dmsimard/python-cachetclient/commit/1a17d1bc244f282271dcbf94dbf61d0d7bf49ad7

Thanks

**Comment by dmsimard** [comment]
Hi, I'll check it out later today. Thanks.

**Comment by dmsimard** [comment]
@janboll 0.2.3 is tagged and released to pypi.
